# Generated by Django 6.0.7 on 2026-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('LOYER', 'Loyer'), ('TRANSPORT', 'Transport'), ('SALAIRE', 'Salaire'), ('ELECTRICITE', 'Électricité'), ('INTERNET', 'Internet'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-date_enregistrement'],
            },
        ),
    ]
