# Generated by Django 6.0.7 on 2026-09-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_depense_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=20),
        ),
    ]
