# Generated by Django 6.0.7 on 2026-08-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_backfill_boutique_par_defaut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acces', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_support', to=settings.AUTH_USER_MODEL)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_support', to='tenants.boutique')),
            ],
            options={
                'ordering': ['-date_acces'],
            },
        ),
    ]
