# Generated by Django 6.0.7 on 2026-08-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_accessupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('duree_jours', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('EN_ATTENTE', 'En attente')], default='ACTIF', max_length=20)),
                ('alerte_envoyee', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, default='', max_length=100)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='tenants.boutique')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.formuleabonnement')),
            ],
        ),
    ]
