# Generated by Django 6.0.7 on 2026-08-29 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_formuleabonnement_abonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_token', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='tenants.boutique')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.formuleabonnement')),
            ],
        ),
    ]
