# Generated by Django 6.1 on 2026-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_seed_formule_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementabonnement',
            name='url_paiement',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
