# Generated by Django 6.0.7 on 2026-09-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_paiementabonnement_montant_attendu_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuleabonnement',
            name='palier',
            field=models.CharField(choices=[('ESSENTIEL', 'Essentiel'), ('PREMIUM', 'Premium')], max_length=20, null=True),
        ),
    ]
