# Generated by Django 6.0.7 on 2026-09-22 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_formuleabonnement_palier_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='profil',
            unique_together={('user', 'boutique')},
        ),
    ]
