# Generated by Django 6.0.7 on 2026-08-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_alter_parametresboutique_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresboutique',
            name='nom_boutique',
            field=models.CharField(default='iwiShop', max_length=150),
        ),
    ]
