# Generated by Django 6.0.7 on 2026-09-02 13:39

import django.core.validators
import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_alter_parametresboutique_nom_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresboutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message="Formats d'image acceptés : JPG, JPEG, PNG, WEBP."), tenants.validators.valider_taille_image]),
        ),
    ]
