# Generated by Django 6.0.7 on 2026-09-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_alter_parametresboutique_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresboutique',
            name='seuil_dette_retard_jours',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
