# Generated by Django 6.0.7 on 2026-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0006_parametresboutique_seuil_dette_retard_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresboutique',
            name='limite_questions_assistant_par_jour',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
