# Generated by Django 6.0.7 on 2026-07-31 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='suppliers.fournisseur')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchases.achat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_achat', to='products.produit')),
            ],
        ),
    ]
