# Generated by Django 6.0.7 on 2026-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_ligneachat_facteur_conversion_applique_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20),
        ),
    ]
