# Generated by Django 6.0.7 on 2026-09-02 09:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_achat_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneachat',
            name='prix_unitaire_achat',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
