# Generated by Django 6.0.7 on 2026-09-02 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_ligneachat_prix_unitaire_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneachat',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
