# Generated by Django 6.0.7 on 2026-10-02 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_backfill_achat_montant_paye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('motif_correction', models.TextField(blank=True, default='')),
                ('mode_paiement', models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30, null=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='purchases.achat')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paiement_corrige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='purchases.paiementfournisseur')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['date_paiement', 'id'],
            },
        ),
    ]
