# Generated by Django 6.0.7 on 2026-08-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_mouvementstock_boutique'),
        ('tenants', '0002_backfill_boutique_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.boutique'),
        ),
    ]
