# Generated by Django 6.0.7 on 2026-09-02 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_mouvementstock_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
