# Generated by Django 6.0.7 on 2026-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categorie_boutique'),
        ('tenants', '0010_alter_paiementabonnement_montant_attendu_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('boutique', 'nom'), name='unique_categorie_nom_par_boutique'),
        ),
    ]
