# Generated by Django 6.0.7 on 2026-09-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_alter_produitprix_options'),
        ('sales', '0018_alter_client_options'),
        ('tenants', '0013_alter_formuleabonnement_palier_notnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('stock_bas', 'Stock bas'), ('dette_retard', 'Dette en retard')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('destinataire_role', models.CharField(choices=[('tous', 'Propriétaire et employés'), ('proprietaire', 'Propriétaire uniquement')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.boutique')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.produit')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.vente')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
