# Generated by Django 6.0.7 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, default='Client comptoir', max_length=150, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monnaie_rendue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], default='ESPECES', max_length=30)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_vente', models.CharField(choices=[('UNITE', 'Unité'), ('DOUZAINE', 'Douzaine')], default='UNITE', max_length=20)),
                ('prix_applique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='products.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.vente')),
            ],
        ),
    ]
