# Generated by Django 6.0.7 on 2026-08-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_backfill_unites_prix'),
        ('sales', '0003_alter_lignevente_boutique_alter_vente_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='products.unitevente'),
        ),
    ]
