# Generated by Django 6.0.7 on 2026-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_lignevente_unite_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='facteur_conversion_applique',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
