# Generated by Django 6.0.7 on 2026-08-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_lignevente_facteur_conversion_applique_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='type_vente',
            field=models.CharField(choices=[('UNITE', 'Unité'), ('DOUZAINE', 'Douzaine'), ('PERSONNALISE', 'Personnalisé')], default='UNITE', max_length=20),
        ),
    ]
