# Generated by Django 6.0.7 on 2026-08-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_lignevente_type_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDEE', max_length=20),
        ),
    ]
