# Generated by Django 6.0.7 on 2026-09-02 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_backfill_unitevente_est_systeme'),
        ('sales', '0011_vente_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='products.produit'),
        ),
    ]
