# Generated by Django 6.0.7 on 2026-09-02 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_vente_montant_paye_alter_vente_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
