# Generated by Django 6.0.7 on 2026-09-03 05:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    # Ajout pur (nullable, aucune donnée touchée) - contrairement à
    # 0007-0009 (facteur_conversion_applique), il n'y a volontairement PAS
    # de migration de backfill ici : reconstituer prix_achat_unitaire pour
    # les lignes existantes à partir de Produit.prix_achat courant
    # recréerait exactement le bug corrigé (un coût actuel n'est pas un
    # coût historique). Les lignes antérieures à cette migration restent
    # NULL indéfiniment - voir sales.models.LigneVente.prix_achat_unitaire.
    # Réversible : `migrate sales 0014` supprime le champ sans perte, aucune
    # donnée n'ayant été écrite dessus par cette migration.

    dependencies = [
        ('sales', '0014_alter_lignevente_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='prix_achat_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
