# Generated by Django 6.0.7 on 2026-09-11 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_lignevente_prix_achat_unitaire'),
        ('tenants', '0010_alter_paiementabonnement_montant_attendu_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='cle_idempotence',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='creee_hors_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vente',
            name='horodatage_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='stock_ajuste_manuellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(condition=models.Q(('cle_idempotence__isnull', False)), fields=('boutique', 'cle_idempotence'), name='unique_cle_idempotence_par_boutique'),
        ),
    ]
