# Generated by Django 6.0.7 on 2026-09-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_vente_montant_du_vente_statut_paiement_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation']},
        ),
    ]
