# Generated by Django 6.0.7 on 2026-09-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='motif_correction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='remboursement_corrige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='sales.remboursement'),
        ),
    ]
