# Generated by Django 6.0.7 on 2026-09-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remboursement_motif_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30, null=True),
        ),
    ]
