# Generated by Django 6.0.7 on 2026-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
