# Generated by Django 6.0.7 on 2026-08-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_produit_boutique'),
        ('tenants', '0003_accessupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('facteur_conversion', models.DecimalField(decimal_places=3, max_digits=10)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_vente', to='tenants.boutique')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('boutique', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ProduitPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_par_unite', to='products.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unitevente')),
            ],
            options={
                'unique_together': {('produit', 'unite')},
            },
        ),
    ]
