# Generated by Django 6.0.7 on 2026-08-18 16:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_backfill_unites_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitevente',
            name='est_systeme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitevente',
            name='facteur_conversion',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
