# Generated by Django 6.0.7 on 2026-09-02 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_produit_prix_achat_alter_produit_prix_douzaine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_en_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_minimum',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
