# Generated by Django 6.0.7 on 2026-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_categorie_nom_and_more'),
        ('products', '0011_alter_produit_quantite_en_stock_and_more'),
        ('tenants', '0010_alter_paiementabonnement_montant_attendu_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('boutique', 'reference'), name='unique_produit_reference_par_boutique'),
        ),
    ]
