# Generated by Django 6.0.7 on 2026-09-02 13:39

import django.core.validators
import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_produit_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message="Formats d'image acceptés : JPG, JPEG, PNG, WEBP."), tenants.validators.valider_taille_image]),
        ),
    ]
