# Generated by Django 6.0.7 on 2026-09-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_produit_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitprix',
            options={'ordering': ['id']},
        ),
    ]
